"""Valores padrão definidos em 00-contexto-geral.md."""

WIDTH = 10
HEIGHT = 20
GRAVITY_SECONDS = 0.7
INITIAL_LOCK_DELAY_SECONDS = 0.8
MIN_LOCK_DELAY_SECONDS = 0.2
LOCK_DELAY_REDUCTION_SECONDS = 0.05
LOCK_DELAY_INTERVAL_SECONDS = 30
MAX_CATCH_UP_STEPS = 4
MAX_GARBAGE_PER_LOCK = 4
MAX_PENDING_GARBAGE = 40
SCORE_BY_LINES = (0, 100, 300, 500, 800)
ATTACK_BY_LINES = (0, 0, 1, 2, 4)
MIN_TERMINAL_WIDTH = 80
MIN_TERMINAL_HEIGHT = 28
